name: Compile Firmware

on:
    pull_request:
        paths:
            - firmware/*.yaml
        branches:
            - main
    push:
        branches:
            - main
        paths:
            - firmware/*.yaml
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: esphome/build-action@v1
              with:
                yaml_file: firmware/fan-controller-v1.yaml
