name: Compile Firmware

on:
    pull_request:
        paths:
            - firmware/*.yaml
        branches:
            - main
    push:
        branches:
            - main
        paths:
            - firmware/*.yaml
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: esphome/build-action@v1
              id: firmware-build
              with:
                yaml_file: firmware/fan-controller-v1.yaml
            - run: |
                mkdir output
                mv "${{ steps.firmware-build.outputs.name }}" output/
            - uses: actions/upload-artifact@v3.1.2
              with:
                name: fan-controller-v1
                path: output
